#!/usr/bin/env python3
"""Sigma is for sum"""


def summation_i_squared(n):
    """Calculates the sum of integers from 1 to n.

    Returns:
        None if n is not a positive integer.
        Otherwise, returns the sum.
    """
    if not isinstance(n, int) or n < 1:
        return None

    return sum(range(1, n + 1))
